name: Bug report
description: Report a problem or defect with the AI Infrastructure Content Generator
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please provide as much detail as possible so we can reproduce the issue.
  - type: textarea
    id: description
    attributes:
      label: Summary
      description: A clear and concise description of the bug.
      placeholder: Briefly explain what went wrong.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide the exact steps so we can reproduce the problem.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: It actually...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Logs, screenshots, environment details, or links that help explain the issue.
      placeholder: |
        - Framework version: 0.2.0
        - Operating system:
        - Python version:
        - Additional notes:
